---
page-layout: article
---
## Ardian Pradipta

I'm a Software Engineer. Currently working at [Samsung SDS Asia Pacific](https://www.samsungsds.com/), Singapore.

## Tech Stacks
- Java, Python, Javascript

- Infra setup (Docker, K8S, VM) 

- Azure (AKS, Key Vault, CosmosDB, DevOps, Pipelines, etc.)

- Version Control like svn and git

## Current Interest
- Data engineering / ML engineering, 

  Since I have quite a lot of experience in building API and data transformation, I always wonder how do my company process this kind of data, how they assess this data, how they give recommendation, etc. 
  Well, I have long journey ahead.

## Side activity
- ✨Finally✨ commited to some course of AI Engineering and Korean course.

- I created [salary calculator](https://github.com/rdnpradipta/salary-calculator-id) for Indonesian Worker.

  I know it's just only one simple website 👉👈 But I have more plans for my upcoming projects!

- I love to play game occasionally.

## Links
Have something in mind? 
  
- Drop me a [message](mailto:hi@rdnpradipta.com)

- Or reach me on [Twitter](https://twitter.com/rdnpradipta)
